src/Entity/Lesson.php
<?php

namespace App\Entity;

use App\Repository\LessonRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: LessonRepository::class)]
class Lesson
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $lesson_content = null;

    #[ORM\Column(nullable: true)]
    private ?int $serial_number = null;

    #[ORM\ManyToOne(inversedBy: 'lesson')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Course $course = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getLessonContent(): ?string
    {
        return $this->lesson_content;
    }

    public function setLessonContent(string $lesson_content): static
    {
        $this->lesson_content = $lesson_content;

        return $this;
    }

    public function getSerialNumber(): ?int
    {
        return $this->serial_number;
    }

    public function setSerialNumber(?int $serial_number): static
    {
        $this->serial_number = $serial_number;

        return $this;
    }

    public function getCourse(): ?Course
    {
        return $this->course;
    }

    public function setCourse(?Course $course): static
    {
        $this->course = $course;

        return $this;
    }
}

src/Form/LessonType.php
<?php

namespace App\Form;

use App\Entity\Course;
use App\Entity\Lesson;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormConfigBuilderInterface;
use Symfony\Component\Validator\Constraints\Range;

class LessonType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, [
                'label' => 'Название',
                'constraints' => [
                    new NotBlank(message: 'Эта строка не может быть пустой'),
                    new Length(['max'=>50], maxMessage:'Название не должно превышать 50 символов')
                ]
            ])
            ->add('lesson_content', TextareaType::class, [
                'label' => 'Содержание урока',
                'constraints' => [
                    new NotBlank(message: 'Эта строка не может быть пустой'),
                    new Length(['max'=>1000], maxMessage:'Содержание урока 1000 символов')
                ]
            ])
            ->add('serial_number', TextType::class, [
                'label' => 'Номер урока',
                'constraints' => [
                    new NotBlank(message: 'Эта строка не может быть пустой'),
                    new Range(
                        notInRangeMessage: 'Значение поля должно быть в пределах от 1 до 500',
                        min: 1,
                        max: 500
                    )
                ]
            ])
            ->add('course', HiddenType::class, [
                'data' => null,
                'disabled' => 'true',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Lesson::class,
        ]);
    }
}

src/Controller/LessonController.php
<?php

namespace App\Controller;

use App\Entity\Course;
use App\Repository\CourseRepository;
use App\Entity\Lesson;
use App\Form\LessonType;
use App\Repository\LessonRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route('/lessons')]
class LessonController extends AbstractController
{
    #[Route('/', name: 'app_lesson_index', methods: ['GET'])]
    public function index(LessonRepository $lessonRepository): Response
    {
        return $this->render('lesson/index.html.twig', [
            'lessons' => $lessonRepository->findAll(),
        ]);
    }

    #[IsGranted('ROLE_SUPER_ADMIN')]
    #[Route('/{id}/new/', name: 'app_lesson_new', methods: ['GET', 'POST'])]
    public function new(Request $request, Course $course, int $id, CourseRepository $courseRepository, EntityManagerInterface $entityManager): Response
    { 
        $lesson = new Lesson();
        $course = $courseRepository->find(['id'=>$id]);
        $lesson->setCourse($course);
        $form = $this->createForm(LessonType::class, $lesson);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($lesson);
            $entityManager->flush();

            return $this->redirectToRoute('app_course_show', ['id' => $lesson -> getCourse()->getId()], Response::HTTP_SEE_OTHER);
        }

        return $this->render('lesson/new.html.twig', [
            'lesson' => $lesson,
            'form' => $form,
            'course' => $course,
        ]);
    }

    #[IsGranted('ROLE_USER')]
    #[Route('/{id}', name: 'app_lesson_show', methods: ['GET'])]
    public function show(Lesson $lesson): Response
    {
        return $this->render('lesson/show.html.twig', [
            'lesson' => $lesson,
        ]);
    }

    #[IsGranted('ROLE_SUPER_ADMIN')]
    #[Route('/{id}/edit', name: 'app_lesson_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Lesson $lesson, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(LessonType::class, $lesson);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_course_show', ['id' => $lesson -> getCourse()->getId()], Response::HTTP_SEE_OTHER);
        }

        return $this->render('lesson/edit.html.twig', [
            'lesson' => $lesson,
            'form' => $form,
        ]);
    }

    #[IsGranted('ROLE_SUPER_ADMIN')]
    #[Route('/{id}', name: 'app_lesson_delete', methods: ['POST'])]
    public function delete(Request $request, Lesson $lesson, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$lesson->getId(), $request->getPayload()->get('_token'))) {
            $entityManager->remove($lesson);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_course_show', ['id' => $lesson -> getCourse()->getId()], 
        Response::HTTP_SEE_OTHER);
    }
}

templates/lesson/_delete_form.html.twig
<form method="post" action="{{ path('app_lesson_delete', {'id': lesson.id}) }}" onsubmit="return confirm('Вы уверены, что хотите удалить этот урок?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ lesson.id) }}">
    <button class="btn btn-outline-danger mt-3">Удалить</button>
</form>

templates/lesson/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary mt-3" class="btn">{{ button_label|default('Сохранить') }}</button>
{{ form_end(form) }}

templates/lesson/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Редактировать урок{% endblock %}

{% block body %}
    <h1>Редактировать урок</h1>

    {{ include('lesson/_form.html.twig', {'button_label': 'Сохранить'}) }}

    {{ include('lesson/_delete_form.html.twig') }}
    
    <a class="btn btn-outline-secondary mt-3" href="{{ path('app_course_show', {'id': lesson.course.id}) }}">Вернуться к списку уроков</a>

{% endblock %}

templates/lesson/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Lesson index{% endblock %}

{% block body %}
    <h1>Lesson index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Lesson_content</th>
                <th>Serial_number</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for lesson in lessons %}
            <tr>
                <td>{{ lesson.id }}</td>
                <td>{{ lesson.name }}</td>
                <td>{{ lesson.lessonContent }}</td>
                <td>{{ lesson.serialNumber }}</td>
                <td>
                    <a href="{{ path('app_lesson_show', {'id': lesson.id}) }}">show</a>
                    <a href="{{ path('app_lesson_edit', {'id': lesson.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_lesson_new') }}">Create new</a>
{% endblock %}

templates/lesson/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Создание нового урока{% endblock %}

{% block body %}
    <h1>Создание нового урока</h1>

    {{ include('lesson/_form.html.twig') }}

    <a class="btn btn-outline-secondary mt-3" href="{{ path('app_course_show', {'id': course.id}) }}">Вернуться к списку уроков</a>
{% endblock %}

templates/lesson/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ lesson.name }}{% endblock %}

{% block body %}
    <h1>{{ lesson.name }}</h1>

    
    <a style="text-decoration: none;" class="link-body-emphasis link-offset-2 link-underline-opacity-25 link-underline-opacity-75-hover" href="{{ path('app_course_show', {'id': lesson.course.id}) }}">{{ lesson.course.name }}</a>
    
    <div class="d-grid gap-2 d-md-flex" style="display:flex">
    {% if is_granted('ROLE_SUPER_ADMIN') %}
        <a class="btn btn-outline-warning mt-3" href="{{ path('app_lesson_edit', {'id': lesson.id}) }}">Редактировать</a>
        {{ include('lesson/_delete_form.html.twig') }}
    {% endif %}
    </div>    
        <div class="border mt-3 p-4 rounded-2">
            {{ lesson.lessonContent }}
        </div>
        {% if is_granted('ROLE_SUPER_ADMIN') %}
            <a class="btn btn-outline-secondary mt-3" href="{{ path('app_course_show', {'id': lesson.course.id}) }}">Вернуться к списку уроков</a>
        {% endif %}

{% endblock %}